name: Build & Deploy Frontend

on:
  push:
    branches: [ "main", "tutoring-rebrand" ]
  workflow_dispatch: {}

# Prevent duplicate runs from racing each other
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # CI sanity build on the runner (Node 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build Frontend (CI sanity check)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Deploy & build on server with Node 20 (via nvm), clean install, vite build
      - name: Deploy via SSH (build on server with Node 20)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            BRANCH="${GITHUB_REF_NAME:-main}"
            echo "Deploying branch: $BRANCH"

            # Ensure Node 20 on the server (install nvm if missing)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] || curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            . "$NVM_DIR/nvm.sh"
            nvm install 20
            nvm use 20
            echo "Using Node $(node -v) and npm $(npm -v)"

            # Sync repo
            cd /var/www/jameswallace.tech
            if [ ! -d ".git" ]; then
              git clone git@github.com:OpusLearning/JamesWallace.tech.git .
            fi
            git config --global --add safe.directory /var/www/jameswallace.tech
            git fetch origin "$BRANCH"
            git checkout "$BRANCH" || git checkout -b "$BRANCH" "origin/$BRANCH"
            git pull --ff-only origin "$BRANCH"

            # Clean install & build with Vite
            cd frontend
            rm -rf node_modules package-lock.json
            npm cache clean --force
            npm ci
            npx vite build

            # Reload web server
            sudo systemctl reload nginx || true

