name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
      - tutoring-rebrand

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # safe with Vite

      - name: Install and Build Frontend (CI sanity check)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy via SSH (build on server)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            BRANCH="${GITHUB_REF_NAME:-main}"
            echo "Deploying branch: $BRANCH"

            cd /var/www/jameswallace.tech
            # ensure repo is present
            if [ ! -d ".git" ]; then
              git clone git@github.com:OpusLearning/JamesWallace.tech.git .
            fi

            # fetch and switch to the pushed branch
            git fetch origin "$BRANCH"
            git checkout "$BRANCH" || git checkout -b "$BRANCH" "origin/$BRANCH"
            git pull origin "$BRANCH"

            # build frontend
            cd frontend
            npm ci
            npm run build

            # reload web server
            sudo systemctl reload nginx || true
